version: "3.9"

services:
  backend:
    container_name: another_node_container
    image: node
    build: .
    ports:
      - 3000:8080 #maquinaLocal:conteiner
    environment: [
        PGUSER=abkuratomi,
        PGPASSWORD=12345,
        PGDATABASE=defaultdb,
        PGHOST=db,
      ] #mascarar esses dados sensíveis
    depends_on:
      - db

  db:
    container_name: another_postgres_container
    image: postgres
    ports: [5432:5432]
    environment: [
        POSTGRES_USER=abkuratomi,
        POSTGRES_PASSWORD=12345,
        POSTGRES_DB=defaultdb,
      ] #idem
