version: "3.9"

services:
  # backend:
  #   image: node:latest
  #   restart: always
  #   build: .
  #   ports:
  #     - 3000:4000 #maquinaLocal:conteiner
  #   # volumes:
  #   #   - .:/code # mapeia o diretório atual para oa do container. aí o build só precisa ser feito 1 vez
  #   environment: [
  #       PGUSER=postgres,
  #       PGPASSWORD=12345,
  #       PGDATABASE=typeorm_test,
  #       PGHOST=db,
  #     ] #mascarar esses dados sensíveis
  #   depends_on:
  #     - db

  db:
    image: postgres
    restart: always
    ports: [5431:5432]
    environment: [
        POSTGRES_USER=postgres,
        POSTGRES_PASSWORD=12345,
        POSTGRES_DB=typeorm_test,
      ] #idem

  adminer:
    image: adminer
    restart: always
    ports: [8080:8080]
