version: "3.9"

services:
  backend:
    image: node:latest
    restart: always
    build: .
    ports:
      - 3000:4000 #maquinaLocal:conteiner
    environment: [
        PGUSER=abkuratomi,
        PGPASSWORD=12345,
        PGDATABASE=defaultdb,
        PGHOST=db,
      ] #mascarar esses dados sensíveis
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    ports: [5431:5432]
    environment: [
        POSTGRES_USER=abkuratomi,
        POSTGRES_PASSWORD=12345,
        POSTGRES_DB=defaultdb,
      ] #idem

  adminer:
    image: adminer
    restart: always
    ports: [8080:8080]
